modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/terrarium-earth/${github_name}/issues"

[[mods]]
modId = "cadmus"
version = "${version}"
displayName = "Cadmus"
updateJSONURL = "https://api.modrinth.com/updates/${modrinth_id}/forge_updates.json"
displayURL = "https://modrinth.com/mod/cadmus"
logoFile = "icon.png"
authors = "Alex Nijjar, ThatGravyBoat"
credits = ""
description = "Modern Chunk Claiming Mod!"
displayTest="IGNORE_ALL_VERSION"

[[dependencies.cadmus]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cadmus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cadmus]]
modId = "resourcefullib"
mandatory = true
versionRange = "[${resourcefullib_version},)"
ordering = "NONE"
side = "BOTH"