modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/terrarium-earth/cadmus/issues"

[[mods]]
modId = "cadmus"
version = "${version}"
displayName = "Cadmus"
updateJSONURL = "https://api.modrinth.com/updates/fEWKxVzh/forge_updates.json"
displayURL = "https://modrinth.com/mod/cadmus"
logoFile = "icon.png"
authors = "Alex Nijjar, ThatGravyBoat"
credits = ""
description = "A land claiming mod that allows users to claim land to protect your home from thieves, bandits and monsters, and admins to claim land with region flags and advanced protection!"
displayTest="IGNORE_ALL_VERSION"

[[mixins]]
config = "cadmus-common.mixins.json"
[[mixins]]
config = "cadmus.mixins.json"

[[dependencies.cadmus]]
modId = "neoforge"
mandatory = true
versionRange = "[20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cadmus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cadmus]]
modId = "resourcefullib"
mandatory = true
versionRange = "[2.2.1,)"
ordering = "NONE"
side = "BOTH"