modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/terrarium-earth/cadmus/issues"

[[mods]]
modId = "cadmus"
version = "${version}"
displayName = "Cadmus"
updateJSONURL = "https://api.modrinth.com/updates/fEWKxVzh/forge_updates.json"
displayURL = "https://modrinth.com/mod/cadmus"
logoFile = "icon.png"
authors = "Alex Nijjar, ThatGravyBoat"
credits = ""
description = "A land claiming mod that allows users to claim land to protect your home from thieves, bandits and monsters, and admins to claim land with region flags and advanced protection!"
displayTest="IGNORE_ALL_VERSION"

[[mixins]]
config = "cadmus-common.mixins.json"
[[mixins]]
config = "cadmus.mixins.json"

[[dependencies.cadmus]]
modId = "neoforge"
type="required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cadmus]]
modId = "minecraft"
type="required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cadmus]]
modId = "resourcefullib"
type="required"
versionRange = "[2.4.6,)"
ordering = "NONE"
side = "BOTH"